### ISSUE TITLE
Server error while trying to view more submission pages

### ISSUE THREAD

**Issue by avdg** [aichallenge/aichallenge#345] opened 2011-10-30 17:51 UTC
This page gives me a 500 error http://aichallenge.org/profile_submissions.php?user=1737&page=1

To get to this page, go to a user profile with more than 10 submissions like http://aichallenge.org/profile.php?user=1737 and click on "View more" at the bottom of the page.

I don't know yet if this is a bug, or (a not implemented) feature.

**Comment by Janzert** [comment] 2011-10-30 20:05
Sorry, I broke it earlier. Should be fixed now.

**Closed as completed by Janzert** 2011-10-30 20:05 UTC

**Comment by ypb** [comment] 2011-10-30 20:30
nah, it still looks broken. besides not showing any sort of table or other content (i don't know how it's supposed to have looked) it's not even displaying user_id in the href.

perhaps variable dereference inside quoted quotes isn't such an echoic idea?!?

**Comment by Janzert** [comment] 2011-10-30 21:13
Maybe try refreshing/clearing your browser cache? The page is loading fine for me.

**Comment by Janzert** [comment] 2011-10-30 21:18
Ahh, ypb I think I see what you're talking about now. It's not the original bug reported here about a server 500 error. But an incomplete page for users other than the logged in user.

**Comment by ypb** [comment] 2011-10-30 21:20
heh, i'd ask you to do the same thing. i tried browsing several other contestants with more than 10 submissions in another browser that did not see those pages for sure before and behavior is as i described it: zilch, not even a user number in the user profile href. but that would indicate that user_id is not NULL and the code enters the if...

i know, weird. perhaps server side is doing some caching... /hmm.

**Comment by Janzert** [comment] 2011-10-30 21:26
Ok, found the cause of your report as well ypb. It was a completely unrelated problem caused by recent persistent login changes. Should also be fixed now.

**Comment by ypb** [comment] 2011-10-30 21:30
yup, works, now. over and out.
