### ISSUE TITLE
server_setup.py expects python-mysqldb to be already installed

### ISSUE THREAD

**Issue by amstan** [aichallenge/aichallenge#117] opened 2011-05-22 21:45 UTC
server_setup.py installs python-mysqldb at some point, but it immediately tries to use it. This is no possible, since the script has to be reloaded for that import to work.

**Comment by Janzert** [comment] 2011-06-08 16:16
Since the import isn't attempted until after the module has been installed it should work. At least it seems to when I do a setup, including from fresh ec2 instances.

**Comment by Janzert** [comment] 2011-06-17 21:37
I've done several install from a fresh OS without being able to reproduce this so I'm closing it for now. Feel free to reopen if someone finds a way to reproduce.

**Closed as completed by Janzert** 2011-06-17 21:37 UTC
