### ISSUE TITLE
cutoff works bad

### ISSUE THREAD

**Issue by TTrumpeTT** [aichallenge/aichallenge#234] opened 2011-08-01 11:39 UTC
Look at this game: http://aichallengebeta.hypertriangle.com/visualizer.php?game=116777&user=476
bot TrumpeT totaly dominated the game. At the end it has 93 ants, enemy has 1
But it ended at the last (third) place. Cutoff 150 is too small, or cutoff alghoritm is stupid.
Cutting off the game when actual leader has lowest score?

**Comment by McLeopold** [comment] 2011-09-10 00:23
Yes, this is bad.  This issue is a duplicate of issue #219.

**Closed as completed by McLeopold** 2011-09-10 00:23 UTC
