### ISSUE TITLE
Add C++0x support with new file name extension

### ISSUE THREAD

**Issue by jonathanasdf** [aichallenge/aichallenge#309] opened 2011-10-21 06:41 UTC
The only difference between this and C++ is every call to g++ must have the -std=c++0x option set.

**Comment by AlvinMinring** [comment] 2011-10-24 06:48
Seconded - this would be nice to have.

**Comment by ghost** [comment] 2011-10-26 11:39
I think thay do not know that this issue exist.

**Comment by ghost** [comment] 2011-10-26 11:42
The problem is that thay are using gcc 4.5. So c++11 will be of little use.

**Comment by AlvinMinring** [comment] 2011-10-27 19:02
It'd still give access to things like unordered_map, which would be nice.

**Comment by ghost** [comment] 2011-10-29 09:32
But you can send your make files... so where is the problem?

**Comment by AlvinMinring** [comment] 2011-10-29 12:18
Makefiles are not used - take a look at the server's source code, or _try_ things before assuming them to be true.

**Comment by Storyyeller** [comment] 2011-10-29 15:59
This feature would be extremely helpful. Decltype/Auto alone is a lifesaver.

**Comment by ghost** [comment] 2011-10-29 19:15
I took this from starter package README.txt
"If you add any additional .cc files to your bot, you will need to alter the Makefile to include them. If you submit your bot with the Makefile included, the server will attempt to use this when compiling your bot, otherwise it will revert back to the auto compile script that is available on the contests github site."

**Comment by Storyyeller** [comment] 2011-10-29 19:27
I submitted a makefile with -std=c++0x enabled, but it gave compiler errors. So something is wrong, and it would appear to be the readme.

**Comment by ghost** [comment] 2011-10-30 10:27
Wich version of gcc do you use? Because 4.6 have much wider support of c++11

**Comment by Storyyeller** [comment] 2011-10-30 16:14
I was using auto, which is supported even in gcc 4.4, and the server uses 4.5, so that's not the problem. The readme is clearly wrong here.

**Comment by Storyyeller** [comment] 2011-11-04 20:40
By the way, this was added under the filename cpp, so the issue can be closed.

**Comment by Zannick** [comment] 2011-11-13 20:43
FYI the starter readme is not correct regarding the Makefile: the compiler script on the contest server does not use it at all.

Closed as we have C++11 support now for bots submitted with MyBot.cpp.

**Closed as completed by Zannick** 2011-11-13 20:43 UTC
