### ISSUE TITLE
Match-making SQL uses the same player as seed every game

### ISSUE THREAD

**Issue by flagcapper** [aichallenge/aichallenge#192] opened 2011-06-20 03:08 UTC
Currently "xtile2" is playing every single game at a rate of about one game per minute: 

http://aichallengebeta.hypertriangle.com/profile.php?user=211

He also appears to have the newest account with a functioning bot (possibly the most recent upload? I had something happen to me before where I uploaded a bot and started playing games very rapidly.)

Either way, I can't access the database so it's hard to tell what exactly the problem is, but it probably has something to do with the "order by" clause starting at line 29 in this query:

https://github.com/aichallenge/aichallenge/blob/epsilon/sql/2_generate_matchup.sql

**Comment by zaphus** [comment] 2011-06-20 05:32
This is majorly broken, I'm trying to understand how the SQL is supposed to be working but the way I read it I figured something like this might end up happening.
This needs to be fixed ASAP, even random seeding would be better than the current system.

**Comment by zaphus** [comment] 2011-06-20 05:50
Extra info:   xtile2 (user 211) seems to be the highest numbered valid entry at the moment, with all after it being invalid - this may be part of the reason.
it's also not clear if they are the seed or if they are being picked because it (wrongly) thinks they have just uploaded

**Comment by Janzert** [comment] 2011-06-20 16:50
This is pretty certainly a duplicate of issue #179

**Comment by McLeopold** [comment] 2011-06-21 23:51
It's a dup, and the dup is fixed.

**Closed as completed by McLeopold** 2011-06-21 23:51 UTC
